language: bash
sudo: required
services:
  - docker
before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats curl
  - docker pull busybox
  - docker pull panubo/vsftpd
script:
  - bats test_backup.bats
